### ISSUE TITLE
Can't pair with iTunes.

### ISSUE THREAD

**Issue by larkov** [edc1591/alfred-itunes-dj#3]
iTunes just returns "The passcode you entered was incorrect". I've tried to do the pairing several times  now with the same result. Any help appreciated.

**Comment by evandcoleman** [comment]
Open the [debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/), try again and post whatever gets output.

**Comment by larkov** [comment]
Here is the output. 

And I'm running on  macOS 10.12.2 beta and iTunes 12.5.3.17.
—
Starting debug for 'iTunes DJ'

[2016-11-18 17:35:46][input.scriptfilter] <items><item uid='' valid='yes'><title>Pair Alfred With iTunes</title><arg>{&quot;alfredworkflow&quot;:{&quot;arg&quot;:&quot;PAIR&quot;,&quot;variables&quot;:{&quot;pin&quot;:&quot;0338&quot;}}}</arg><subtitle>Enter pin 0338 in iTunes</subtitle><icon>icon.png</icon></item></items>
[2016-11-18 17:36:08][input.scriptfilter] Processing output of 'utility.filter' with arg 'PAIR'
[2016-11-18 17:36:08][input.scriptfilter] Processing output of 'utility.filter' with arg 'PAIR'
[2016-11-18 17:36:08][utility.filter] Processing output of 'output.notification' with arg 'PAIR'
[2016-11-18 17:36:08][output.notification] Processing output of 'action.script' with arg ‘PAIR'

**Comment by larkov** [comment]
I probably should have mentioned that I'm running on macOS 10.12.2 beta and iTunes 12.5.3.17 too.

**Comment by evandcoleman** [comment]
Hmm, I don't think that should make a difference. Try this:
1. If you have multiple rubies installed, switch to the system ruby (`rvm system` for `rvm`)
2. Enter the following commands:

```
$ sudo gem install dacpclient
$ dacpclient login
```

That should prompt you to go through the pairing process. Let me know if that works. If it does, it's probably a bug in my workflow.

**Comment by larkov** [comment]
Didn’t work. I’m including the output from terminal too.

---

Last login: Fri Nov 18 17:33:40 on console
MacBook-Pro:~ lari$ cd /Users/lari/Library/Application\ Support/Alfred\ 3/Alfred.alfredpreferences/workflows/user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211/
MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$ rvm system
-bash: rvm: command not found
MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$ sudo gem install dacpclient
Password:
Fetching: dnssd-2.0.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed dnssd-2.0.1
Fetching: plist-3.1.0.gem (100%)
Successfully installed plist-3.1.0
Fetching: dmapparser-0.2.0.gem (100%)
Successfully installed dmapparser-0.2.0
Fetching: fuzzy_match-2.1.0.gem (100%)
Successfully installed fuzzy_match-2.1.0
Fetching: dacpclient-0.3.4.gem (100%)
Successfully installed dacpclient-0.3.4
Parsing documentation for dnssd-2.0.1
Installing ri documentation for dnssd-2.0.1
Parsing documentation for plist-3.1.0
Installing ri documentation for plist-3.1.0
Parsing documentation for dmapparser-0.2.0
Installing ri documentation for dmapparser-0.2.0
Parsing documentation for fuzzy_match-2.1.0
Installing ri documentation for fuzzy_match-2.1.0
Parsing documentation for dacpclient-0.3.4
Installing ri documentation for dacpclient-0.3.4
Done installing documentation for dnssd, plist, dmapparser, fuzzy_match, dacpclient after 1 seconds
5 gems installed
MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$ dacpclient login
/usr/local/bin/dacpclient:23:in `load': cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/dacpclient-0.3.4/bin/dacpclient (LoadError)
    from /usr/local/bin/dacpclient:23:in`<main>'
MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$

**Comment by evandcoleman** [comment]
Hmm, strange. Does `gem list | grep dacpclient` output anything?

**Comment by larkov** [comment]
Here it is.

## And thanks for your patience and help. 

MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$ gem list | grep dacpclient
dacpclient (0.3.4)

**Comment by evandcoleman** [comment]
No problem! I want to make sure this isn't affecting others as well.

Try this:
1. Right-click the workflow in Alfred's preferences, click "Open in Terminal".
2. Using the system Ruby again, type the following commands:
   
   ```
   $ irb
   $ require_relative 'itunesdj'
   $ dj = ITunesDJ.new
   $ dj.pair [1,2,3,4]
   ```
3. If you don't see any errors, switch to iTunes and try to pair using "1234" as the pin.

**Comment by larkov** [comment]
After dj.pair it just hangs. And iTunes keeps telling it’s the wrong password.

---

MacBook-Pro:~ lari$ cd /Users/lari/Library/Application\ Support/Alfred\ 3/Alfred.alfredpreferences/workflows/user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211/
MacBook-Pro:user.workflow.5459758A-D634-4ACD-9BF3-56F28B9D6211 lari$ irb
irb(main):001:0> require_relative 'itunesdj'
=> true
irb(main):002:0> dj = ITunesDJ.new
=> #<ITunesDJ:0x007fbbae09b778 @config={"client_name"=>"Alfred iTunes DJ", "host"=>"localhost", "known_services"=>[], "guid"=>"51DB0530689FAE33"}>
irb(main):003:0> dj.pair [1,2,3,4]

**Comment by evandcoleman** [comment]
It's supposed to hang while it waits for the pairing process to be completed through iTunes. Have you tried rebooting your machine and trying again?

**Comment by larkov** [comment]
Yes, Tried rebooting again with the same result.

**Comment by evandcoleman** [comment]
Hmm, I'm really not sure what the issue is. Are you able to pair successfully using the Remote iOS app? It sounds like this may be an issue with [ruby-dacpclient](https://github.com/jurriaan/ruby-dacpclient).

**Comment by larkov** [comment]
Hi.

Yes I was able to connect the Remote iOS app. And after that I tried connecting itunes-dj again and it worked as it should. Don’t know what the problem was though :(

/Lari Kovanen

**Comment by evandcoleman** [comment]
Heh, strange. Glad you got it working!
