### ISSUE TITLE
Increase number of results?

### ISSUE THREAD

**Issue by christianmagill** [edc1591/alfred-itunes-dj#5]
Would it be possible to change the number of results returned? Sometimes I remember a song is on an album or by an artist but I don't necessarily remember what the name is without seeing it. With 8 results there's a good chance it won't be in the list.

Perhaps this could be an option?

**Comment by evandcoleman** [comment]
I suppose a variable can be added to set the number of results. I can add this later today.

**Comment by evandcoleman** [comment]
Added in [2.1](https://github.com/edc1591/alfred-itunes-dj/releases/tag/2.1).
